version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXTAUTH_SECRET: secret
        BASE_API: http://localhost:8080/api/v1
    ports:
      - "3000:3000"
